twitter/urls.py
from django.urls import path
from django.urls import include
from django.views import generic
from twitter.views import MainPageView
from twitter import views

app_name = 'twitter'
urlpatterns = [
    path('', MainPageView.as_view(template_name='twitter/index.html'),
         name='index'),
    path('register', views.RegisterView.as_view(),name='register'),
    path('compose/', views.ComposeView.as_view(), name='compose'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('user/<int:pk>/', views.AuthorDetailView.as_view(),name='author-detail'),
    path('tweet/<int:pk>/', views.TweetDetailView.as_view(), name='tweet-detail')
]

twitter/models.py
from django.db import models
from django.contrib.auth.models import User

TWITER_MAX_LENGTH = 280

# Create your models here.
class Tweet(models.Model):
    content = models.CharField(max_length=TWITER_MAX_LENGTH)
    creation_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)


    def __str__(self):
        return f'[{self.creation_date}] ' \
               f'TWEET by {self.author}: {self.content[:20]}'

twitter/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from twitter import models


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class TweetForm(forms.ModelForm):
    class Meta:
        model = models.Tweet
        fields = ['content']
        widgets = {
            'content': forms.Textarea()
        }

twitter/views.py
from django.shortcuts import render, redirect
from twitter.models import Tweet
from django.views import View
from django.views.generic.list import ListView
from twitter import forms
from twitter import models
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView
from django.urls import reverse_lazy



# Create your views here.

class MainPageView(ListView):
    template_name = 'twitter/index.html'
    context_object_name = 'tweets'

    def get_queryset(self):
        return Tweet.objects.all().order_by('-creation_date')


class RegisterView(View):
    form_class = forms.UserRegisterForm
    template_name = 'twitter/register.html'

    def get(self, request):
        return render(request, 'twitter/register.html',
                      {'form': forms.UserRegisterForm()})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            password = form.cleaned_data['password1']
            user.set_password(password)
            user.save()
            return redirect('/')

        return render(request, self.template_name, {'form': form})

class ComposeView(LoginRequiredMixin, CreateView):
    model = models.Tweet
    form_class = forms.TweetForm
    success_url = reverse_lazy('twitter:index')

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class ProfileView(LoginRequiredMixin, View):

    def get(self, request):
        tweets = models.Tweet.objects.filter(
            author=request.user).order_by('-creation_date')
        return render(request, 'twitter/profile.html', {'tweets': tweets})

class AuthorDetailView(View):
    def get(self, request, pk):
        tweets = Tweet.objects.filter(author=pk).order_by('-creation_date')
        return render(request, 'twitter/user_tweet.html', {'tweets': tweets})

class TweetDetailView(View):
    model = models.Tweet

class DetailView(View):
    pass

twitter/templates/twitter/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'twitter/main.css' %}">
    <title>Django Twitter clone</title>
</head>

<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="{% url 'twitter:index' %}">Twitter clone</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{% url 'twitter:index' %}">Home</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
                {% if user.is_authenticated %}
                    <a class="nav-item nav-link" href="{% url 'twitter:compose' %}">New Post</a>
                    <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
                {% else %}
                    <a class="nav-item nav-link" href="{% url 'twitter:profile' %}">Profile</a>
                    <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
                    <a class="nav-item nav-link" href="{% url 'twitter:register' %}">Register</a>
                {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
    {% block content %}
    {% endblock %}
    </main>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</body>
</html>

twitter/templates/twitter/index.html
{% extends 'twitter/base.html' %}
{% block content %}
                    <a href="{% url 'twitter:author-detail' tweet.author.pk %}">
                        <small class="text-muted">by {{ tweet.author }}</small>
                    </a>
             <a href="{% url 'twitter:tweet-detail' tweet.pk %}">
                        <small class="text-muted">{{ tweet.creation_date|date:"F d, Y" }}</small>
                    </a>
    {% for tweet in tweets %}
        <article class="media content-section">
            <div class="media-body">
                <div class="article-metadata">
                        <small class="text-muted">{{ tweet.creation_date|date:"F d, Y" }}</small>
                        <small class="text-muted">by {{ tweet.author }}</small>
                </div>
                <p class="article-content">{{ tweet.content }}</p>
            </div>
        </article>
    {% endfor %}
{% endblock content %}

twitter/templates/twitter/login.html
{% extends 'twitter/base.html' %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                {{ form }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Login</button>
                <smal class="text-muted ml-2">
                    <a href="{% url 'password-reset' %}">Forgot Password?</a>
                </smal>
            </div>
        </form>
    </div>
{% endblock content %}

twitter/templates/twitter/logout.html
{% extends 'twitter/base.html' %}
{% block content %}
    <h2>You have been logged out</h2>
    <div class="border-top pt-3">
        <small class="text-muted">
            <a href="{% url 'login' %}">Log in Again</a>
        </small>
    </div>
{% endblock content %}

twitter/templates/twitter/password_reset.html
{% extends 'twitter/base.html' %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>
                {{ form }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Request Password reset</button>
            </div>
        </form>
    </div>
{% endblock content %}

twitter/templates/twitter/profile.html
{% extends 'twitter/base.html' %}
{% load avatar_tags %}
{% block content %}
{% avatar user 65 class="rounded-circle account-img" id="user_avatar" %}
<a href="{% url 'avatar_change' %}">Change your avatar</a>
<h2>Tweets by {{ user.get_username }}</h2>
    {% for tweet in tweets %}
        <article class="media content-section">
            <div class="media-body">
                <div class="article-metadata">
                    <small class="text-muted">{{ tweet.creation_date|date:"F d, Y" }}</small>
                </div>
                <p class="article-content">{{ tweet.content }}</p>
            </div>
        </article>
    {% endfor %}
{% endblock content %}

twitter/templates/twitter/register.html
{% extends 'twitter/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Join today</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Sign Up</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Already Have an Account? <a class="ml-2" href="{% url 'login' %}">Sign in</a>
            </small>
        </div>
    </div>
{% endblock content %}

twitter/templates/twitter/tweet_form.html
{% extends 'twitter/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">What's going on, {{user}}?</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Post</button>
            </div>
        </form>
    </div>
{% endblock content %}

twitter/templates/twitter/user_tweet.html
{% extends 'twitter/base.html' %}
{% load avatar_tags %}
{% block content %}
{% avatar user 65 class="rounded-circle account-img" id="user_avatar" %}
<a href="{% url 'avatar_change' %}">Change your avatar</a>
<h2>Tweets by {{ tweet.author }}</h2>
    {% for tweet in tweets %}
        <article class="media content-section">
            <div class="media-body">
                <div class="article-metadata">
                    <small class="text-muted">{{ tweet.creation_date|date:"F d, Y" }}</small>
                </div>
                <p class="article-content">{{ tweet.content }}</p>
            </div>
        </article>
    {% endfor %}
{% endblock content %}